### ISSUE TITLE
Доступ к серверам через кросс-доменные запросы

### ISSUE THREAD

**Issue by Alexandera0** [BOG8/Backend-basis#1]
Дедлайн: 26.03.2017

**Comment by BOG8** [comment]
Нет зарплаты - нет работы!!! (Свободу попугаям!)

**Comment by BOG8** [comment]
На самом деле, это две разные задачи. В будущем, лучше разные задачи в разные issues класть.

P. S. Хотя может я и не прав)

P. P. S. Да нет, бред какой-то...

**Comment by Alexandera0** [comment]
Хорошо. Поменяю на две разные задачи. Спасибо за комментарий!

**Comment by BOG8** [comment]
Готово, проверяй и закрывай)
